i changed the rule code and restarted server still error not solved Console Error Server
FirebaseError: Missing or insufficient permissions.

Call Stack
4

Hide 4 ignore-listed frame(s)
resolveErrorDev
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js (1845:1)
processFullStringRow
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js (2225:1)
processFullBinaryRow
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js (2213:1)
progress
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js (2459:1)